import Queue from 'bull';

export const AWS_CLOUD_PROVIDER = 'AWS_CLOUD_PROVIDER';
export const AZURE_CLOUD_PROVIDER = 'AZURE_CLOUD_PROVIDER';
export const GOOGLE_CLOUD_PROVIDER = 'GOOGLE_CLOUD_PROVIDER';

export const queues = {
  [AWS_CLOUD_PROVIDER]: new Queue(AWS_CLOUD_PROVIDER, process.env.REDIS_URL),
  [AZURE_CLOUD_PROVIDER]: new Queue(AZURE_CLOUD_PROVIDER, process.env.REDIS_URL),
  [GOOGLE_CLOUD_PROVIDER]: new Queue(GOOGLE_CLOUD_PROVIDER, process.env.REDIS_URL)
};